version: '3.9'
services:
  app:
    container_name: mern-crud-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server